name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: "--out-${NO_FUTURE}format colored-line-number"

  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Test
        run: |
          go run ./build/build.go --target Run-Tests
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-report
          path: reports/junit-test-report.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: reports/junit-test-report.xml
          reporter: java-junit
